### ISSUE TITLE
Feature request: have a onScaleChangedListener to listener the zoom changes.

### ISSUE THREAD

**Issue by adrianolc** [igreenwood/loupe#10]
First congratulations on the project, it's really good and helped me this last week a lot!!

On my app, we have some logic running when the user zooms a picture, so it would be nice to have a callback sending us the scale factor and the X, Y focus. 

I did a fork from the project and add it to make it works for our project, I can open a PR with the suggested changes.

#### Environment

- Library Version: 1.0.2

**Comment by igreenwood** [comment]
Fixed. Please use 1.0.3.
