### ISSUE TITLE
Shared element return animation starting from the screen top left

### ISSUE THREAD

**Issue by adrianolc** [igreenwood/loupe#12]
**Describe the bug**
After swipe up or down to dismiss the activity, the shared image goes to the top left from the screen and the return animation starts from there. 

**To Reproduce**
1. Go to details activity or the activity opened with the shared element scene
2. Scroll down to dismiss
4. The image first go straight to top left screen then the animation return begins

**Expected behavior**
The shared image should keep the position where the user stopped to scroll and the return animation should start from this position

**Environment**
 - Library Version: 1.0.2

**Additional context**
The problem is caused by the `cleanup` method where the properties `imageMatrix` and `y` are setted to `null` and `0` respectively

**Comment by igreenwood** [comment]
Oh... 😭 
Thank you for reporting!
I will fix it soon 👍

**Comment by igreenwood** [comment]
Fixed. Please use 1.0.3.

**Comment by adrianolc** [comment]
> Oh... 😭
> Thank you for reporting!
> I will fix it soon 👍

My pleasure!! Thanks for add the fix :)
