### ISSUE TITLE
Feature Request: ability to programmatically dismiss

### ISSUE THREAD

**Issue by edenman** [igreenwood/loupe#18]
I would like to have the Android back button dismiss the loupe viewer if it is visible.  I can just hide the ImageView and container, but then there's a bunch of listeners still attached and `cleanup()` is private.

**Environment**
 - Library Version: 1.0.2

Let me know if this is something you'd be amenable to and I can create a PR to add this method.

**Comment by igreenwood** [comment]
@edenman 
Nice proposal 😄 
I agree to your idea. Please create the PR 🙌

**Comment by edenman** [comment]
Thanks for the quick merges!  Can I get you to roll another release?  Or are there other changes you want to include?

**Comment by igreenwood** [comment]
@edenman 
I have released 1.2.0, but this changes not included for some reasons(I don't know why 🤔 )  
I will try to deploy another release👍
Just a minute 🙏

**Comment by igreenwood** [comment]
@edenman 
I have released 1.2.1.
Please try it 🙏

**Comment by edenman** [comment]
Hm.
```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.igreenwood:loupe:1.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/igreenwood/loupe/1.2.1/loupe-1.2.1.pom
       - https://jcenter.bintray.com/com/igreenwood/loupe/1.2.1/loupe-1.2.1.pom
       - https://plugins.gradle.org/m2/com/igreenwood/loupe/1.2.1/loupe-1.2.1.pom
       - https://dl.bintray.com/kotlin/kotlin-eap/com/igreenwood/loupe/1.2.1/loupe-1.2.1.pom
     Required by:
         project :app
```

Looks like https://jcenter.bintray.com/com/igreenwood/loupe/ only has up to 1.0.3?

**Comment by igreenwood** [comment]
@edenman 
Sorry for complicated package name. Please use `implementation 'com.igreenwood.loupe:loupe:1.2.1'` (loupe 2 times!)
https://jcenter.bintray.com/com/igreenwood/loupe/loupe/

**Comment by edenman** [comment]
Reading is hard 😭  new version works great, thanks!
