### ISSUE TITLE
Migrate from jCenter to mavenCentral

### ISSUE THREAD

**Issue by mohamed-khaled-hsn** [igreenwood/loupe#29]
Loupe is not available in repositories of mavenCentral.
Please consider publishing it there

JCenter deprecation and end of service: https://developer.android.com/studio/build/jcenter-migration

**Comment by trenthudy** [comment]
+1

**Comment by SrgGrch** [comment]
Any updates here?

**Comment by alexatbooli** [comment]
Polite nudge.

**Comment by mohamed-khaled-hsn** [comment]
Resolved with the release of version: [1.2.2](https://github.com/igreenwood/loupe/releases/tag/1.2.2) 🎉
Make sure you change the dependency name from `com.igreenwood.loupe` to `io.github.igreenwood.loupe`

Many thanks @igreenwood
